### ISSUE TITLE
Use log4j in Picard tools

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/hellbender#146]
Currently, all GATK tools use log4j and all Picard tools use HTSJDK's Log. We should decide on one of these and use it for everything.

**Comment by akiezun** [comment]
@cmnbroad is on it

**Comment by cmnbroad** [comment]
One service in htsjdk logger that we use a lot in the picard tools is the ProgressLogger, which allows the caller to set a threshold "n" so that progress is only logged every "n" SAMRecords. I don't see anything built in to log4j for this so we'll have to reproduce it in the hellbender codebase for log4j. Its not much code but it will duplicate what is htsjdk.

**Comment by cmnbroad** [comment]
Closed by #612.
