### ISSUE TITLE
Profile options for passing reference data to workers in dataflow

### ISSUE THREAD

**Issue by droazen** [broadinstitute/hellbender#490]

**Comment by droazen** [comment]
Options include:

-sharding the reference data + GroupByKey
-embedding reference bases as an attribute in reads
-downloading reference to each worker on demand from a bucket
-containers?

**Comment by lbergelson** [comment]
which option does baking the reference into the containers count as?

**Comment by pgrosu** [comment]
What is the current I/O throughput, the amount of data being pushed and the desired response-time?  Usually keeping read-only data locally is usually faster, but it depends on how frequently it is used.  Otherwise there would be dedicated sharded indexed servers, which would perform part of the repetitive data-processing to increase the response-time back to any workers and returned results.

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#14
