### ISSUE TITLE
PoN creation - Storing it using HDF5

### ISSUE THREAD

**Issue by vruano** [broadinstitute/hellbender#503]
2 man days.

**Comment by vruano** [comment]
@droazen @lbergelson this will require to install hdf5 libs in Travis CI / Coveralls. Is this feasible? Could you try to do it to confirm either way.

**Comment by vruano** [comment]
Otherwise shall we try to pack the libraries up as part of the build? Since we don't have a pure-Java failover implementation I think this option is risky.

**Comment by droazen** [comment]
I'll defer to @lbergelson on that one...

**Comment by lbergelson** [comment]
These libraries are going in hellbender-protected right? Not hellbender base?

**Comment by lbergelson** [comment]
@vruano Is there a specific version of hdf5 we need? It probably isn't easy to automate the install as part of our build, so we will probably have to have a special travis step to install it.  If it's available as a ubuntu package for precise then it won't be an issue, but otherwise it might be a pain.
