### ISSUE TITLE
Double-check validation test

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/hellbender#557]
There's some bad input in the BQSR test; update the input validation test to make sure it can find reads that are malformed in that way.

**Comment by lbergelson** [comment]
The failures were from reads with broken MD tag values.  These were found because `ReadConverter` calls `SequenceUtil.makeReferenceFromAlignment` if the MD tag is found on a read.  It's unlikely this is ever used in normal PICARD/GATK usage so these broken reads were never identified.

**Comment by lbergelson** [comment]
This may be an expensive validation since it necessarily involves parsing the cigar and MD tags. 
This is being done a `SamRecord` -> `Read` conversion since google's `CigarUnit` includes an optional referenceSequence field which may be filled in for SNPs and Deletions.  It effectively replaces the sam MD tag.  This is actually a major improvement over he MD tag, which is an incredibly confusing tag.

**Comment by akiezun** [comment]
this ticket is a bit confusing. What needs to be done here and how will we know it's done?

**Comment by jean-philippe-martin** [comment]
We can close this ticket, both issues is describes are fixed.

The first half is fixed because I have created a new input that the parser can read without tripping over so BQSR now passes (modulo issue #580). 

The second half is now unnecessary. I was suggesting we update GATK so it rejects those inputs outright. @lbergelson convincingly argues that this would be expensive. So instead we can keep on assuming that the user gives us well-formed inputs, but then we have to make sure our own test inputs are well-formed. The newer issue #569 covers this approach.
