### ISSUE TITLE
Fix all dataflow tests and make them mandatory.

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/hellbender#751]
A number of the cloud and bucket tests are failing on google dataflow.  These need to be fixed.  

#750 is a pre-requisite.

Once the tests are fixed we should make these tests mandatory.

**Comment by jean-philippe-martin** [comment]
As @droazen was saying in #656 16 days ago, this is becoming urgent.

It appears this problem has prevented us from noticing a big regression in the Hellbender code that broke  BaseRecalibratorDataflow (possibly because it broke the BAM reader)

**Comment by jean-philippe-martin** [comment]
I just tried `gradle testAll` on the master branch and I see `RefAPISourceUnitTest` failing. 

These regressions make progress a lot harder, and unfairly shift effort from those not writing cloud code to those who are.

What I suggest we do is that instead of having just "bucket" and "cloud" groups, we split into "bucket", "cloud", "bucket_todo" and "cloud_todo".

We make "bucket" and "cloud" mandatory *right now*.

The tests that don't pass, we move to the "_todo" categories. This way the tests that work now will keep on working - otherwise we'll never get out of this mess. Then we can track the number of _todo tests left and make sure they go down.

**Comment by jean-philippe-martin** [comment]
#823 is making good progress in this direction.

**Comment by jean-philippe-martin** [comment]
With #825 we're now at 12 passing cloud tests (mandatory), and 7 todos.

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/hellbender-dataflow#19
